.TH "SCHED" "1" "November 2019" "sched" "User Commands"
.SH NAME
sched \- manage a school class schedule
.SH SYNOPSIS
.B sched
.RB [next|setup]
.SH DESCRIPTION
TODO
.SH AUTHOR
Written by Ben O'Neill <ben@benoneill.xyz>.
.SH BUGS
If any bugs are found, email the author.
.SH COPYRIGHT
Copyright \(co 2019 Ben O'Neill <ben@benoneill.xyz>. License: GNU GPLv3+: GNU GPL
version 3 or later. <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it. There is NO
WARRANTY, to the extent permitted by law.
.SH SEE ALSO
.BR dateutils (1)
